
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import type { Client, KeyContact } from '@/lib/types'; // Ensure KeyContact is imported
import { PlusCircle } from 'lucide-react';

// Simplified schema for the dialog, more details can be added in profile page
const clientFormSchema = z.object({
  companyName: z.string().min(2, 'Company name must be at least 2 characters.'),
  primaryContactName: z.string().min(2, 'Contact name must be at least 2 characters.'),
  primaryContactEmail: z.string().email('Invalid email address.'),
  primaryContactPhone: z.string().optional(),
  industry: z.string().optional(),
  website: z.string().url('Invalid URL. Include http(s)://').optional(),
});

// This FormData is specific to what the dialog collects
export type AddClientFormData = z.infer<typeof clientFormSchema>;

interface AddClientDialogProps {
  onAddClient: (clientData: Omit<Client, 'id' | 'keyContacts' | 'status' | 'lastContact'> & { keyContacts: Pick<KeyContact, 'name' | 'email' | 'phone' | 'role'>[] }) => void;
}

export default function AddClientDialog({ onAddClient }: AddClientDialogProps) {
  const [open, setOpen] = useState(false);
  const form = useForm<AddClientFormData>({
    resolver: zodResolver(clientFormSchema),
    defaultValues: {
      companyName: '',
      primaryContactName: '',
      primaryContactEmail: '',
      primaryContactPhone: '',
      industry: '',
      website: '',
    },
  });

  const handleSubmit = (data: AddClientFormData) => {
    // Transform AddClientFormData to the structure expected by onAddClient
    // which aligns more closely with the full Client type
    const newClientData = {
      companyName: data.companyName,
      industry: data.industry,
      website: data.website,
      keyContacts: [
        {
          // id will be generated by the parent for mock data
          name: data.primaryContactName,
          email: data.primaryContactEmail,
          phone: data.primaryContactPhone,
          role: 'Primary Contact', // Default role
        }
      ],
      // Other fields will be initialized by the parent page
    };
    onAddClient(newClientData as any); // Cast as any due to Omit complexity, parent handles full structure
    form.reset();
    setOpen(false);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <PlusCircle className="mr-2 h-4 w-4" />
          Add Client
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle>Add New Client Company</DialogTitle>
          <DialogDescription>
            Enter core details for the new client company. More details can be added later.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4 py-4">
            <FormField
              control={form.control}
              name="companyName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Company Name</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. Innovatech Ltd." {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="primaryContactName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Primary Contact Name</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. Sarah Connor" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="primaryContactEmail"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Primary Contact Email</FormLabel>
                  <FormControl>
                    <Input type="email" placeholder="e.g. s.connor@example.com" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="primaryContactPhone"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Primary Contact Phone (Optional)</FormLabel>
                  <FormControl>
                    <Input type="tel" placeholder="e.g. (555) 123-4567" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="industry"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Industry (Optional)</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. Technology" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
             <FormField
              control={form.control}
              name="website"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Website (Optional)</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g. https://example.com" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
              <Button type="submit">Save Client</Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
